# netlify.toml - Vite + React
[build]
  command = "npm run build"
  publish = "dist"
  # base = ""  # only set this if your app lives in a subfolder (no leading slash)

# Single Page App fallback (React Router BrowserRouter)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional headers (security + caching examples)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Referrer-Policy = "no-referrer-when-downgrade"
    Cache-Control = "public, max-age=0, must-revalidate"
